local p = require("skull.palette")
local h = require("skull.utils")

local M = {}

local colors = p.colors
local highlight = h.highlight

function M.setup()
	highlight("Cursor", { fg = colors.white, bg = colors.background, gui = "NONE" })
	highlight("IncSearch", { fg = colors.white, bg = colors.background, gui = "ITALIC" })
	highlight("Search", { fg = colors.blue, bg = colors.darker_gray, gui = "ITALIC" })
	highlight("Visual", { fg = colors.green, bg = colors.darker_gray, gui = "ITALIC" })
	highlight("VisualNOS", { fg = colors.green, bg = colors.darker_gray, gui = "ITALIC" })
	highlight("Constant", { fg = colors.gray, bg = colors.dark_gray })
	highlight("DiffAdd", { fg = colors.gray, bg = colors.dark_gray })
	highlight("Number", { fg = colors.light_blue, bg = colors.dark_gray, gui = "BOLD" })
	highlight("Pmenu", { fg = colors.green, bg = colors.darker_gray, gui = "BOLD" })
	highlight("String", { fg = colors.light_gray, bg = colors.dark_gray })
	highlight("CursorColumn", { fg = colors.white, bg = colors.darker_gray })
	highlight("ColorColumn", { fg = colors.darker_gray, bg = colors.darker_gray })
	highlight("CursorLine", { bg = colors.darker_gray })
	highlight("CursorLineNr", { fg = colors.green, bg = colors.darker_gray })
	highlight("Comment", { fg = colors.green, bg = colors.dark_gray, gui = "ITALIC" })
	highlight("DiffChange", { fg = colors.gray, bg = colors.dark_gray })
	highlight("DiffDelete", { fg = colors.gray, bg = colors.dark_gray })
	highlight("DiffText", { fg = colors.gray, bg = colors.dark_gray })
	highlight("Directory", { fg = colors.gray, bg = colors.dark_gray })
	highlight("Error", { fg = colors.gray, bg = colors.dark_gray })
	highlight("Folded", { fg = colors.gray, bg = colors.dark_gray })
	highlight("Function", { fg = colors.green, bg = colors.dark_gray, gui = "BOLD" })
	highlight("Identifier", { fg = colors.gray, bg = colors.dark_gray })
	highlight("Ignore", { fg = colors.gray, bg = colors.dark_gray })
	highlight("Label", { fg = colors.gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("LineNr", { fg = colors.medium_gray, bg = colors.dark_gray })
	highlight("MatchParen", { fg = colors.background, bg = colors.green })
	highlight("ModeMsg", { fg = colors.gray, bg = colors.dark_gray })
	highlight("MoreMsg", { fg = colors.gray, bg = colors.dark_gray })
	highlight("NonText", { fg = colors.gray, bg = colors.dark_gray })
	highlight("Normal", { fg = colors.gray, bg = colors.dark_gray })
	highlight("PmenuSbar", { fg = colors.gray, bg = colors.dark_gray })
	highlight("PmenuSel", { fg = colors.gray, bg = colors.dark_gray, gui = "ITALIC" })
	highlight("PmenuThumb", { fg = colors.gray, bg = colors.dark_gray })
	highlight("PreProc", { fg = colors.gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("Special", { fg = colors.special_gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("Operator", { fg = colors.green, bg = colors.dark_gray, gui = "BOLD" })
	highlight("SpecialKey", { fg = colors.gray, bg = colors.dark_gray, gui = "ITALIC" })
	highlight("Statement", { fg = colors.gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("StatusLine", { fg = colors.background, bg = colors.green })
	highlight("StatusLineNC", { fg = colors.gray, bg = colors.dark_gray, gui = "ITALIC" })
	highlight("StorageClass", { fg = colors.gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("Structure", { fg = colors.gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("TabLine", { fg = colors.gray, bg = colors.dark_gray })
	highlight("TabLineFill", { fg = colors.gray, bg = colors.dark_gray })
	highlight("TabLineSel", { fg = colors.gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("Title", { fg = colors.gray, bg = colors.dark_gray })
	highlight("Todo", { fg = colors.gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("Todo", { fg = colors.gray, bg = colors.dark_gray, gui = "UNDERLINE" })
	highlight("Type", { fg = colors.gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("TypeDef", { fg = colors.gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("Underlined", { fg = colors.gray, bg = colors.dark_gray, gui = "UNDERLINE" })
	highlight("VertSplit", { fg = colors.gray, bg = colors.dark_gray })
	highlight("WarningMsg", { fg = colors.gray, bg = colors.dark_gray })
	highlight("WildMenu", { fg = colors.gray, bg = colors.dark_gray })
	highlight("cucumberTags", { fg = colors.gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("htmlTagN", { fg = colors.gray, bg = colors.dark_gray, gui = "BOLD" })
	highlight("rubySymbol", { fg = colors.gray, bg = colors.dark_gray })
	highlight("NonText", { fg = colors.medium_gray, bg = colors.dark_gray })
	highlight("Directory", { fg = colors.green, bg = colors.dark_gray, gui = "BOLD" })
	highlight("SignColumn", { fg = "NONE", bg = "NONE" })

	-- Dashboard

	highlight("DashboardShortCut", { fg = colors.blue })
	highlight("DashboardHeader", { fg = colors.green })
	highlight("DashboardCenter", { fg = colors.green })
	highlight("DashboardFooter", { fg = colors.green })
	highlight("DashboardKey", { fg = colors.green })
	highlight("DashboardDesc", { fg = colors.green })
	highlight("DashboardIcon", { fg = colors.green, gui = "BOLD" })
end

return M
